# Generated by Django 5.2.5 on 2026-02-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='section',
        ),
    ]
