# Generated by Django 5.2.5 on 2026-01-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='GradeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradesubmission', to='academic.enrollment')),
            ],
        ),
    ]
