# Generated by Django 5.2.5 on 2026-02-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_section_academicstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstatus',
            name='cumulative_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
