# Generated by Django 5.2.5 on 2026-02-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_sectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.PositiveSmallIntegerField()),
                ('room', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: restrict dormitory to a department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dormitories', to='academic.department')),
            ],
            options={
                'ordering': ('gender', 'block', 'room'),
                'unique_together': {('block', 'room', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='DormitoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dormitory.dormitory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_assignments', to='academic.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-semester__start_date',),
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
