# Generated by Django 6.0.3 on 2026-03-30 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dormitory',
            unique_together={('block', 'room', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='dormitoryassignment',
            unique_together={('student', 'semester')},
        ),
    ]
